title:              Doron Chapnitsky
email:              chapnitskydoron@gmail.com
description:        Variety of projects by me
author:             Doron Chapnitsky
baseurl:            ""
url:                "https://chapnitsky.github.io"

# Social Profiles
twitter_username:   
github_username:    chapnitsky
facebook_username:  
instagram_username: doronchap
linkedin_username: doronchapnitsky

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
